#!/usr/bin/env bash

#
# Health checks for cluster monitoring using HTTP messages
#

LOG="${LOG:-/dev/null}"
HTTP_WAIT=${HTTP_WAIT:-0.1} # wait before closing tcp session
DISABLE_FILE=${DISABLE_FILE:-/var/tmp/node.disable}

# CUSTOM HEALTH CHECKS ARE ADDED HERE
node_health_check() {
  # Examples:
  # ps --no-headers -C nginx &>$LOG || res_err 'No nginx process is running'
  #
  # ss -ltn state listening | grep 3000 &>$LOG || res_err 'Socket 3000 is not listening'
  #
  # out=$(mysqladmin --connect-timeout=1 ping 2>$LOG)
  # [[ "$out" == 'mysqld is alive' ]] || res_err "Mysql ping failed: $out"

  res_ok
}

http_msg() {
  local msg="$1"

  echo -en 'Content-Type: text/plain\r\n'
  echo -en 'Connection: close\r\n'
  echo -en "Content-Length: ${#msg}\r\n"
  echo -en '\r\n' # necessary content delimeter
  echo -en "$msg"
}

res_err() {
  local msg="ERROR: $1"

  echo -en 'HTTP/1.1 503 Service Unavailable\r\n'
  http_msg "$msg"

  # must wait for ack from client
  sleep $HTTP_WAIT
  exit 1
}

res_ok() {
  local msg='OK'

  echo -en 'HTTP/1.1 200 OK\r\n'
  http_msg "$msg"

  sleep $HTTP_WAIT
  exit
}

# main ####

if [[ "$1" == '-h' || "$1" == '--help' ]]; then
  echo "Usage: $0 [enable|disable]"
  exit
elif [[ "$1" == 'disable' || "$1" == '--disable' ]]; then
  touch "$DISABLE_FILE"
elif [[ "$1" == 'enable' || "$1" == '--enable' ]]; then
  rm -f "$DISABLE_FILE"
fi

if [ -e "$DISABLE_FILE" ]; then
  res_err "Cluster node is manually disabled by $(stat -c '%U' $DISABLE_FILE)"
fi

node_health_check
